using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using hotelier_core_app.Migrations;

#nullable disable

namespace hotelier_core_app.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408000000_EnsureReservationExpenseTable")]
    public partial class EnsureReservationExpenseTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: creates the table only if it doesn't already exist.
            // This handles cases where the previous migration recorded in history
            // but the DDL failed to execute on the target database.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS public.""ReservationExpense"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ReservationId"" bigint NOT NULL,
                    ""Description"" character varying(255) NOT NULL,
                    ""Category"" character varying(50) NULL,
                    ""Quantity"" integer NOT NULL DEFAULT 1,
                    ""UnitPrice"" numeric NOT NULL,
                    ""Amount"" numeric NOT NULL,
                    ""CreatedBy"" character varying(200) NULL,
                    ""CreationDate"" timestamp with time zone NOT NULL,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    CONSTRAINT ""FK_ReservationExpense_Reservation_ReservationId""
                        FOREIGN KEY (""ReservationId"")
                        REFERENCES public.""Reservation"" (""Id"")
                        ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ReservationExpense_ReservationId""
                ON public.""ReservationExpense"" (""ReservationId"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS public.""ReservationExpense"";");
        }
    }
}
